---
- name: Install tmux
  become: true
  ansible.builtin.package:
    name: tmux
    state: present

- name: Install Tmux Plugin Manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: "{{ tmux_tpm_dir }}"
    depth: 1

- name: Create config directory
  ansible.builtin.file:
    path: "{{ tmux_config_dir }}"
    state: directory

- name: Copy configuration
  ansible.builtin.file:
    src: "{{ tmux_dotfiles_dir }}/tmux.conf"
    dest: "{{ tmux_config_dir }}/tmux.conf"
    state: link
    force: true
